[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.21'
optimizer = true
optimizer_runs = 200
assertions_revert = true
remappings = [
    "dss-test/=lib/dss-allocator/lib/dss-test/src/",
    "usds/=lib/usds/",
    "sdai/=lib/sdai/",
    "spark-psm/=lib/spark-psm/",
    "xchain-helpers/=lib/xchain-helpers/",
]

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
